spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studio_medico
    username: root
    password: nthzDha2!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update

