spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico
    username: root
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    it.develhope.StudioMedico.serviceImpl: ERROR