spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico
    username: root
    password: Elpipita96!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
